### ISSUE TITLE
shDerefSimple missing in bash keyword group

### ISSUE THREAD

**Issue by sheodox** [alajmo/pinto#11]
First, this site is great! It's helped me remake my theme I've been used to using for years in other editors.

I noticed there doesn't seem to be a `shDerefSimple` keyword in the bash keyword list. It's in the example script, but unless I missed it I didn't see it in the keyword list.
![image](https://user-images.githubusercontent.com/3468630/128656353-3b138bf6-9d7a-4644-a3e2-2ecb3f1da298.png)

This can be worked around by manually editing the keyword group FWIW.

**Comment by alajmo** [comment]
Thank you for your kind words and for finding the missing keyword! 

It seems I'm using old syntax files, I've updated them now for `bash` and a bunch of other languages.

**Comment by sheodox** [comment]
Thank you for the quick response!
